version: "3.6"
services:
  # Nginx
  nginx:
    container_name: nginx
    build: nginx
    environment:
      SERVER_IP: 'localhost:3000'
    ports:
      - "80:80"
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/url-shortener
      POSTGRES_DB: url-shortener
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  url-shortener-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/url-shortener-api
    command: npm start
    working_dir: /usr/src/url-shortener-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/url-shortener
      REDIS_URI: redis://redis:6379

